### PR TITLE
Wait helper: pending operation can be already included

### LINKED ISSUE #297: Wait helper failed to find the operation in the block
```
2022-04-26 01:56:12.162Z INFO batbit_refunds Going to refund: tz1bXXbm9QRLGa4jPHRBHmaNfWnRwz29RhF1 5.0 for 10 purchases
2022-04-26 01:56:12.162Z INFO batbit_refunds Going to refund: tz1ZtFsbnrYNqGidYg6kGVmg86SC77KoCX3g 0.5 for 1 purchases
2022-04-26 01:56:12.162Z INFO batbit_refunds Going to refund: tz1dfuAP4p7EHcr5j1UX9tjCin9GfUUD3qwA 1.5 for 3 purchases
2022-04-26 01:57:44.940Z INFO shell Operation oopwxbhhcCfCm27Gg5aJ16jCG93f9BYLY71untJoEbktZQ55MpA is still in mempool
2022-04-26 01:57:45.476Z INFO shell Sleep 1 seconds until block BKoiyfqQPe5CAP1EgNUZBaE9vMUyAQ3kkYmZ49sjRezFeW8c8EE is superseded
2022-04-26 01:57:59.133Z INFO shell Found new block BLrykDwgtriDEnXufrtR6hEf4Yc1xD3kSrpMjupVcve4NjM2eRx (8 sec delay)
2022-04-26 01:58:00.088Z INFO shell Operation oopwxbhhcCfCm27Gg5aJ16jCG93f9BYLY71untJoEbktZQ55MpA is still in mempool
2022-04-26 01:58:00.614Z INFO shell Sleep 15 seconds until block BLrykDwgtriDEnXufrtR6hEf4Yc1xD3kSrpMjupVcve4NjM2eRx is superseded
2022-04-26 01:58:16.147Z INFO shell Found new block BMMcivYhsijhCNq7PqqTVKyFAKWgCgow1WBF8K2NbUs8Xxv35aC (0 sec delay)
2022-04-26 01:58:17.102Z INFO shell Operation oopwxbhhcCfCm27Gg5aJ16jCG93f9BYLY71untJoEbktZQ55MpA is still in mempool
2022-04-26 01:58:17.622Z INFO shell Sleep 28 seconds until block BMMcivYhsijhCNq7PqqTVKyFAKWgCgow1WBF8K2NbUs8Xxv35aC is superseded
2022-04-26 01:58:59.770Z INFO shell Found new block BLFXqDccVR3qU5WWbcg5snvm5Xrvhj9Pf4cTQLEEsj9MoEzK3bR (9 sec delay)
2022-04-26 01:59:00.786Z INFO shell Operation oopwxbhhcCfCm27Gg5aJ16jCG93f9BYLY71untJoEbktZQ55MpA has left mempool
2022-04-26 01:59:01.856Z INFO shell Sleep 14 seconds until block BLFXqDccVR3qU5WWbcg5snvm5Xrvhj9Pf4cTQLEEsj9MoEzK3bR is superseded
2022-04-26 01:59:33.318Z INFO shell Found new block BLqKukSP5E5N7DY98cZXE3XYyh4kfJ6pGqVVrWFLegMKNdJdppi (11 sec delay)
2022-04-26 01:59:34.352Z INFO shell Sleep 11 seconds until block BLqKukSP5E5N7DY98cZXE3XYyh4kfJ6pGqVVrWFLegMKNdJdppi is superseded
2022-04-26 01:59:50.399Z INFO shell Found new block BMck3FWMg4XMQYt8fk7gqLqKPJxUbUqQnXNJSBpuZDQKMrNiuBb (3 sec delay)
2022-04-26 01:59:51.448Z INFO shell Sleep 24 seconds until block BMck3FWMg4XMQYt8fk7gqLqKPJxUbUqQnXNJSBpuZDQKMrNiuBb is superseded
2022-04-26 02:00:15.982Z INFO shell Found new block BKzUW4dTKbt37C7ZA9GhrbHrEr8zjv88jTrAFf1qobmDBFGTJty (0 sec delay)
2022-04-26 02:00:17.028Z INFO shell Sleep 28 seconds until block BKzUW4dTKbt37C7ZA9GhrbHrEr8zjv88jTrAFf1qobmDBFGTJty is superseded
2022-04-26 02:00:59.165Z INFO shell Found new block BMVhUdKa6Pk8JVGR2Supx6LhtFudGPfP6P11Lz1jQMEUEHnhzvE (9 sec delay)
2022-04-26 02:01:00.209Z INFO shell Sleep 15 seconds until block BMVhUdKa6Pk8JVGR2Supx6LhtFudGPfP6P11Lz1jQMEUEHnhzvE is superseded
2022-04-26 02:01:15.734Z INFO shell Found new block BL6ZLyYxCtjsNYGPgWFWbSxkkTxPLivbe6FjSNt8k4GbRP8gBAg (0 sec delay)
2022-04-26 02:01:16.800Z INFO shell Sleep 29 seconds until block BL6ZLyYxCtjsNYGPgWFWbSxkkTxPLivbe6FjSNt8k4GbRP8gBAg is superseded
2022-04-26 02:01:59.947Z INFO shell Found new block BLFkWpwXggjJWYDMyZxXDTYgNVER7yPnEypicNgQ63JzFqxcPAF (9 sec delay)
2022-04-26 02:02:00.984Z INFO shell Sleep 15 seconds until block BLFkWpwXggjJWYDMyZxXDTYgNVER7yPnEypicNgQ63JzFqxcPAF is superseded
2022-04-26 02:02:16.517Z INFO shell Found new block BLzqUVMWhrJvu3BHrjAuv4bVF195X8M2Ck2nefY1XfCnFNXWxwy (0 sec delay)
2022-04-26 02:02:17.578Z INFO shell Sleep 28 seconds until block BLzqUVMWhrJvu3BHrjAuv4bVF195X8M2Ck2nefY1XfCnFNXWxwy is superseded
2022-04-26 02:02:59.741Z INFO shell Found new block BMQP49K7WpjyB3bLrkP5xVzto2NmnQmqyxc3pSPsB2sxF56MTeE (9 sec delay)
2022-04-26 02:03:00.790Z INFO shell Sleep 15 seconds until block BMQP49K7WpjyB3bLrkP5xVzto2NmnQmqyxc3pSPsB2sxF56MTeE is superseded
2022-04-26 02:03:16.320Z INFO shell Found new block BLR6gYmtYGxtEv2K2bwSSzPNt9B1EuSPE8ak28VWu9nor8F5SvY (0 sec delay)
2022-04-26 02:03:17.368Z INFO shell Sleep 28 seconds until block BLR6gYmtYGxtEv2K2bwSSzPNt9B1EuSPE8ak28VWu9nor8F5SvY is superseded
2022-04-26 02:03:59.522Z INFO shell Found new block BLxjaZrFg4kwGLCnquXM8x4JwrLqHRDGXWa6Gow7fss2E83Bm3Y (9 sec delay)
2022-04-26 02:04:00.563Z INFO shell Sleep 15 seconds until block BLxjaZrFg4kwGLCnquXM8x4JwrLqHRDGXWa6Gow7fss2E83Bm3Y is superseded
2022-04-26 02:04:16.108Z INFO shell Found new block BL8Qf99s7YqaYWxLHzqvYqARvmCb7yp5vdhQ9FZFzG9bQeHgvFV (0 sec delay)
2022-04-26 02:04:17.138Z INFO shell Sleep 28 seconds until block BL8Qf99s7YqaYWxLHzqvYqARvmCb7yp5vdhQ9FZFzG9bQeHgvFV is superseded
2022-04-26 02:04:59.618Z INFO shell Found new block BMP7GNpFBBJPqPHPefFVaoEkrvtpSDGhNiSAbN6iMayFB5iBFhi (9 sec delay)
2022-04-26 02:05:00.692Z INFO shell Sleep 15 seconds until block BMP7GNpFBBJPqPHPefFVaoEkrvtpSDGhNiSAbN6iMayFB5iBFhi is superseded
2022-04-26 02:05:32.889Z INFO shell Found new block BLaeEQaFSGJ2f5rku8akvzMGPnKhpXrXMWzndvGX4wVvroB2uFU (11 sec delay)
2022-04-26 02:05:33.933Z INFO shell Sleep 12 seconds until block BLaeEQaFSGJ2f5rku8akvzMGPnKhpXrXMWzndvGX4wVvroB2uFU is superseded
2022-04-26 02:05:49.477Z INFO shell Found new block BLShYsrp9uDUD1XG5kGWxpsbRE2KBXdS5SpSb5HFZsCLQT2pkbU (2 sec delay)
2022-04-26 02:05:50.544Z INFO shell Sleep 25 seconds until block BLShYsrp9uDUD1XG5kGWxpsbRE2KBXdS5SpSb5HFZsCLQT2pkbU is superseded
2022-04-26 02:06:32.692Z INFO shell Found new block BLhfFCWe76TRFa2gBLNBYEwZTbbG4mf6qC7tey7pPBPKrPY6Mag (11 sec delay)
2022-04-26 02:06:33.732Z INFO shell Sleep 12 seconds until block BLhfFCWe76TRFa2gBLNBYEwZTbbG4mf6qC7tey7pPBPKrPY6Mag is superseded
2022-04-26 02:06:49.286Z INFO shell Found new block BMCumW74LLqSzXSr5QHpVjHe4WrPGFW7FpbTXwWWdeDePzKU631 (2 sec delay)
2022-04-26 02:06:50.327Z INFO shell Sleep 25 seconds until block BMCumW74LLqSzXSr5QHpVjHe4WrPGFW7FpbTXwWWdeDePzKU631 is superseded
2022-04-26 02:07:15.870Z INFO shell Found new block BL1xZWiESUDygoAXbbidLvsL9eiXkw1PXqpvwJYL5yZbNZeo2AV (0 sec delay)
2022-04-26 02:07:16.910Z INFO shell Sleep 29 seconds until block BL1xZWiESUDygoAXbbidLvsL9eiXkw1PXqpvwJYL5yZbNZeo2AV is superseded
2022-04-26 02:08:00.083Z INFO shell Found new block BLe818yPSoBhjqeaYU46VLykmLpHJyU5VjFoxMV9gXfSVSQwTfP (9 sec delay)
2022-04-26 02:08:01.118Z INFO shell Sleep 14 seconds until block BLe818yPSoBhjqeaYU46VLykmLpHJyU5VjFoxMV9gXfSVSQwTfP is superseded
2022-04-26 02:08:33.789Z INFO shell Found new block BLcPmdiw71dFVSR1SkZX1iwZWU9RFnSFuVgW5fLXeLy2vqdDEx8 (12 sec delay)
2022-04-26 02:08:34.839Z INFO shell Sleep 11 seconds until block BLcPmdiw71dFVSR1SkZX1iwZWU9RFnSFuVgW5fLXeLy2vqdDEx8 is superseded
2022-04-26 02:08:49.371Z INFO shell Found new block BL5o5YdoboVzuwKWsty4WJDMXQj1SFuTkR2q64Z8rYFe65iZoKy (2 sec delay)
2022-04-26 02:08:50.405Z INFO shell Sleep 25 seconds until block BL5o5YdoboVzuwKWsty4WJDMXQj1SFuTkR2q64Z8rYFe65iZoKy is superseded
2022-04-26 02:09:23.529Z INFO shell Found new block BLziLvmz1QUFh6GNk1LqyXJQ7gEVN8mHJGZbvHVBcTnKvvNLQ77 (5 sec delay)
2022-04-26 02:09:24.581Z INFO shell Sleep 21 seconds until block BLziLvmz1QUFh6GNk1LqyXJQ7gEVN8mHJGZbvHVBcTnKvvNLQ77 is superseded
2022-04-26 02:10:00.012Z INFO shell Found new block BKyvU7bpPgFsJRku37c5Dw4tUF7o3M44WFe38a6CpcE3Bp2ZQHg (9 sec delay)
2022-04-26 02:10:01.072Z INFO shell Sleep 14 seconds until block BKyvU7bpPgFsJRku37c5Dw4tUF7o3M44WFe38a6CpcE3Bp2ZQHg is superseded
2022-04-26 02:10:15.598Z INFO shell Found new block BL7mZvztoX9J9XNFgHRcbtX1KZeb9afoKvuxv7Gg85McrGENpVt (0 sec delay)
2022-04-26 02:10:16.639Z INFO shell Sleep 29 seconds until block BL7mZvztoX9J9XNFgHRcbtX1KZeb9afoKvuxv7Gg85McrGENpVt is superseded
2022-04-26 02:10:59.778Z INFO shell Found new block BLZAUReQnzUqmcYEtSo5nMD7zuQRvQLDADvoVet5cErfiUEfogg (9 sec delay)
2022-04-26 02:11:00.822Z INFO shell Sleep 15 seconds until block BLZAUReQnzUqmcYEtSo5nMD7zuQRvQLDADvoVet5cErfiUEfogg is superseded
2022-04-26 02:11:16.359Z INFO shell Found new block BKmLsbv3PS3688rmigYoCV8JBr6fEB6Jhp8xMEsoM1U7MKxbMtg (0 sec delay)
2022-04-26 02:11:17.417Z INFO shell Sleep 28 seconds until block BKmLsbv3PS3688rmigYoCV8JBr6fEB6Jhp8xMEsoM1U7MKxbMtg is superseded
2022-04-26 02:11:59.560Z INFO shell Found new block BMRPX5PADJkBKvy1TZZkdnSxdT6P2GztMi4zzgWfzaZoahmMQmj (9 sec delay)
2022-04-26 02:12:00.608Z INFO shell Sleep 15 seconds until block BMRPX5PADJkBKvy1TZZkdnSxdT6P2GztMi4zzgWfzaZoahmMQmj is superseded
2022-04-26 02:12:32.765Z INFO shell Found new block BLu1CbHPWedYTCeo72rusJ98QwkEihF5kqJaeCGU6cGzxWtRfUi (11 sec delay)
2022-04-26 02:12:33.804Z INFO shell Sleep 12 seconds until block BLu1CbHPWedYTCeo72rusJ98QwkEihF5kqJaeCGU6cGzxWtRfUi is superseded
2022-04-26 02:12:49.357Z INFO shell Found new block BL7MvMVUPFTzV9a4EP4QmhP2BEBv9P8F7u5QYP2yXQ46omjQfX2 (2 sec delay)
2022-04-26 02:12:50.389Z INFO shell Sleep 25 seconds until block BL7MvMVUPFTzV9a4EP4QmhP2BEBv9P8F7u5QYP2yXQ46omjQfX2 is superseded
2022-04-26 02:13:21.984Z INFO shell Found new block BMShmApZ2Ypm82nAb9dxpk5JpYxRaYqjvbvcvD6BJjpmxt1m4jL (4 sec delay)
2022-04-26 02:13:23.032Z INFO shell Sleep 22 seconds until block BMShmApZ2Ypm82nAb9dxpk5JpYxRaYqjvbvcvD6BJjpmxt1m4jL is superseded
2022-04-26 02:13:59.154Z INFO shell Found new block BLgofrV1XEQohpqCpDGAYs1oQyZ7kWduCuccNqHeub1Gbpg874V (9 sec delay)
2022-04-26 02:14:00.201Z INFO shell Sleep 15 seconds until block BLgofrV1XEQohpqCpDGAYs1oQyZ7kWduCuccNqHeub1Gbpg874V is superseded
2022-04-26 02:14:32.404Z INFO shell Found new block BKy9WbYDUVY9GM1FYVKRtDaEaEUZUKAzsoPPq5qujBMSDFhiX3H (11 sec delay)
2022-04-26 02:14:33.441Z INFO shell Sleep 12 seconds until block BKy9WbYDUVY9GM1FYVKRtDaEaEUZUKAzsoPPq5qujBMSDFhiX3H is superseded
2022-04-26 02:14:49.278Z INFO shell Found new block BLDsFHErKbutz8Tnb9GSmFp6q5vXWbSssu9mmiMpQr3V9QFKu8u (2 sec delay)
2022-04-26 02:14:50.325Z INFO shell Sleep 25 seconds until block BLDsFHErKbutz8Tnb9GSmFp6q5vXWbSssu9mmiMpQr3V9QFKu8u is superseded
2022-04-26 02:15:21.914Z INFO shell Found new block BLw8AWSYqvFdpr2Dy4f2Kg5dpFfDcTYFre7vqDmVJ7DXFqX1Ubu (4 sec delay)
2022-04-26 02:15:22.954Z INFO shell Sleep 23 seconds until block BLw8AWSYqvFdpr2Dy4f2Kg5dpFfDcTYFre7vqDmVJ7DXFqX1Ubu is superseded
2022-04-26 02:16:00.123Z INFO shell Found new block BLFzqbdTMCrymhUnXJ2Hwmh7mQ2Ct2t932GpXAxg5aWbAxdSuDd (9 sec delay)
2022-04-26 02:16:01.153Z INFO shell Sleep 14 seconds until block BLFzqbdTMCrymhUnXJ2Hwmh7mQ2Ct2t932GpXAxg5aWbAxdSuDd is superseded
2022-04-26 02:16:17.208Z INFO shell Found new block BMbhuMTLTtmpS62EkMRcWfcXu6wtP1aX4vT9vtK56Ew3qtL7BJk (1 sec delay)
2022-04-26 02:16:18.261Z INFO shell Sleep 27 seconds until block BMbhuMTLTtmpS62EkMRcWfcXu6wtP1aX4vT9vtK56Ew3qtL7BJk is superseded
2022-04-26 02:16:59.414Z INFO shell Found new block BLQk6g2aKsD1kKFh3SD1EzuvQhSMHnrGgJ4M4kJKxrCriuvzfzJ (9 sec delay)
2022-04-26 02:17:00.470Z INFO shell Sleep 15 seconds until block BLQk6g2aKsD1kKFh3SD1EzuvQhSMHnrGgJ4M4kJKxrCriuvzfzJ is superseded
2022-04-26 02:17:15.998Z INFO shell Found new block BLcdcqiuebwL4aZbfSvRRvr475txrbyXGxz9LxGyejhPVzESZYv (0 sec delay)
2022-04-26 02:17:17.039Z INFO shell Sleep 28 seconds until block BLcdcqiuebwL4aZbfSvRRvr475txrbyXGxz9LxGyejhPVzESZYv is superseded
2022-04-26 02:17:59.191Z INFO shell Found new block BKyddT2XvHY1pPZsHkyefLLs2fiF7xfXsu9WgQN5iuJQH2D4hBo (9 sec delay)
2022-04-26 02:18:00.222Z INFO shell Sleep 15 seconds until block BKyddT2XvHY1pPZsHkyefLLs2fiF7xfXsu9WgQN5iuJQH2D4hBo is superseded
2022-04-26 02:18:15.789Z INFO shell Found new block BKvYAkqfccvUTd8DEiofXyAhjJSyZtH9aPAKLAfn6xsYkN81An1 (0 sec delay)
2022-04-26 02:18:16.847Z INFO shell Sleep 29 seconds until block BKvYAkqfccvUTd8DEiofXyAhjJSyZtH9aPAKLAfn6xsYkN81An1 is superseded
2022-04-26 02:18:59.993Z INFO shell Found new block BLJiUGsdL3sVNsQpsQg1xWmjFpKMmx7z45xA7R9RPBCneE8rh2N (9 sec delay)
2022-04-26 02:19:01.034Z INFO shell Sleep 14 seconds until block BLJiUGsdL3sVNsQpsQg1xWmjFpKMmx7z45xA7R9RPBCneE8rh2N is superseded
2022-04-26 02:19:32.227Z INFO shell Found new block BLYVNGHsSLWQHM67LvV6FQaVoM8f23N22jAwwXx8A264HDFKQnb (11 sec delay)
2022-04-26 02:19:33.258Z INFO shell Sleep 12 seconds until block BLYVNGHsSLWQHM67LvV6FQaVoM8f23N22jAwwXx8A264HDFKQnb is superseded
2022-04-26 02:19:48.956Z INFO shell Found new block BMLZzkfoSUkwtoYT3AzddmFtDqzE7VzqfzEudJkkrxmGevNzd7V (2 sec delay)
2022-04-26 02:19:50.128Z INFO shell Sleep 25 seconds until block BMLZzkfoSUkwtoYT3AzddmFtDqzE7VzqfzEudJkkrxmGevNzd7V is superseded
2022-04-26 02:20:15.664Z INFO shell Found new block BLUkLRoWKDyPngrhv6mNnUfaUiApoCfZBZKryanA9WRtRnNQSFD (0 sec delay)
2022-04-26 02:20:16.736Z INFO shell Sleep 29 seconds until block BLUkLRoWKDyPngrhv6mNnUfaUiApoCfZBZKryanA9WRtRnNQSFD is superseded
2022-04-26 02:20:52.316Z INFO shell Found new block BLoAmK8njLN5N4S53ypZkcaZUSdT913Q4oEvagSBDvHDbosoeHW (4 sec delay)
2022-04-26 02:20:53.368Z INFO shell Sleep 22 seconds until block BLoAmK8njLN5N4S53ypZkcaZUSdT913Q4oEvagSBDvHDbosoeHW is superseded
2022-04-26 02:21:32.546Z INFO shell Found new block BLW4D3daoEW5FnMHgp8annR8SKevk27ghDXhgcq5bVuX98YtWxG (11 sec delay)
2022-04-26 02:21:33.579Z INFO shell Sleep 12 seconds until block BLW4D3daoEW5FnMHgp8annR8SKevk27ghDXhgcq5bVuX98YtWxG is superseded
2022-04-26 02:21:49.141Z INFO shell Found new block BM7LwKD9rg7cjz4WTz5RBqYyfdgekd15Wdy3YhqcysxGFupZrSe (2 sec delay)
2022-04-26 02:21:50.187Z INFO shell Sleep 25 seconds until block BM7LwKD9rg7cjz4WTz5RBqYyfdgekd15Wdy3YhqcysxGFupZrSe is superseded
2022-04-26 02:22:15.729Z INFO shell Found new block BLYoHMm7Uge4oL8oEWfugwg7Q46Ld7PFcdEVhYstVjJR4rGtNGp (0 sec delay)
2022-04-26 02:22:16.760Z INFO shell Sleep 29 seconds until block BLYoHMm7Uge4oL8oEWfugwg7Q46Ld7PFcdEVhYstVjJR4rGtNGp is superseded
2022-04-26 02:22:52.364Z INFO shell Found new block BKniSjWfCDzTAQtV1Pirzz9VYdC6xYBWWTZ8LYWkf9Ay8bAjADq (4 sec delay)
2022-04-26 02:22:53.401Z INFO shell Sleep 22 seconds until block BKniSjWfCDzTAQtV1Pirzz9VYdC6xYBWWTZ8LYWkf9Ay8bAjADq is superseded
2022-04-26 02:23:15.940Z INFO shell Found new block BLBcyFCtbgizPLvxFArK6i9cZAZJAEed3sp1CxaRmMTY58dcWBR (0 sec delay)
2022-04-26 02:23:16.972Z INFO shell Sleep 29 seconds until block BLBcyFCtbgizPLvxFArK6i9cZAZJAEed3sp1CxaRmMTY58dcWBR is superseded
2022-04-26 02:23:52.571Z INFO shell Found new block BLJGm36XXntASBxtqk5NMMeDGRFzX8zMJ5LHdpQ2m5xVk3JZeDM (4 sec delay)
2022-04-26 02:23:53.601Z INFO shell Sleep 22 seconds until block BLJGm36XXntASBxtqk5NMMeDGRFzX8zMJ5LHdpQ2m5xVk3JZeDM is superseded
2022-04-26 02:24:16.237Z INFO shell Found new block BLwx9wNmBSfTW9zsZ536mdvCDGSqMB4b7SE7gqxzX4eJKP7yiWM (0 sec delay)
2022-04-26 02:24:17.271Z INFO shell Sleep 28 seconds until block BLwx9wNmBSfTW9zsZ536mdvCDGSqMB4b7SE7gqxzX4eJKP7yiWM is superseded
2022-04-26 02:24:52.168Z INFO shell Found new block BLwdQJZGq3UqsFJu2k1QitWATS5bQKFMRi6QU521gTjasM2PHQi (4 sec delay)
2022-04-26 02:24:53.207Z INFO shell Sleep 22 seconds until block BLwdQJZGq3UqsFJu2k1QitWATS5bQKFMRi6QU521gTjasM2PHQi is superseded
2022-04-26 02:25:15.746Z INFO shell Found new block BLx4LLuKu5nTMcFqbEKUUkjX5ndetbxc3UVfdMXuXA2GgUsARC8 (0 sec delay)
2022-04-26 02:25:16.793Z INFO shell Sleep 29 seconds until block BLx4LLuKu5nTMcFqbEKUUkjX5ndetbxc3UVfdMXuXA2GgUsARC8 is superseded
2022-04-26 02:25:59.932Z INFO shell Found new block BM1ujiPGZzZVGus38dodpzv75yBvsEw1NCsdkciFfTQvFKa16Nb (9 sec delay)
2022-04-26 02:26:00.977Z INFO shell Sleep 15 seconds until block BM1ujiPGZzZVGus38dodpzv75yBvsEw1NCsdkciFfTQvFKa16Nb is superseded
2022-04-26 02:26:33.134Z INFO shell Found new block BKzFiFoRsX4HzNdRE8vMUFB3pDQ27y6EUGLLuy6otFf8v53DykB (11 sec delay)
2022-04-26 02:26:34.183Z INFO shell Sleep 11 seconds until block BKzFiFoRsX4HzNdRE8vMUFB3pDQ27y6EUGLLuy6otFf8v53DykB is superseded
2022-04-26 02:26:50.237Z INFO shell Found new block BMb9P1SZGBGkS9a46hUfceeB7zHCjcNB5RAs43YY5ZWMgwvF3BA (3 sec delay)
2022-04-26 02:26:51.287Z INFO shell Sleep 24 seconds until block BMb9P1SZGBGkS9a46hUfceeB7zHCjcNB5RAs43YY5ZWMgwvF3BA is superseded
2022-04-26 02:27:15.828Z INFO shell Found new block BMbQkq5S68PLW2zf1URD1AzCpo3ijxmyikGj5tHGsbvH6WJavND (0 sec delay)
2022-04-26 02:27:16.348Z WARNING transfer Transaction costs would have been fees: 0.008754, gas: 0.675000
Traceback (most recent call last):
  File "/mnt/c/Users/beebl/PycharmProjects/teos-project-tools/util/transfer.py", line 45, in _send_batch
    log.debug(pp.pformat(op.send(min_confirmations=1, ttl=60)))
  File "/home/moch/.pyenv/versions/3.8.13/envs/taco-tezos-project-tools/lib/python3.8/site-packages/pytezos/operation/group.py", line 339, in send
    res = opg.inject(min_confirmations=min_confirmations, num_blocks_wait=ttl)
  File "/home/moch/.pyenv/versions/3.8.13/envs/taco-tezos-project-tools/lib/python3.8/site-packages/pytezos/operation/group.py", line 404, in inject
    operations = self.shell.wait_operations(
  File "/home/moch/.pyenv/versions/3.8.13/envs/taco-tezos-project-tools/lib/python3.8/site-packages/pytezos/rpc/shell.py", line 188, in wait_operations
    raise StopIteration('Only %d of %d operations were included, stopping', len(operations), len(opg_hashes))
StopIteration: ('Only %d of %d operations were included, stopping', 0, 1)
Traceback (most recent call last):
  File "/mnt/c/Users/beebl/PycharmProjects/teos-project-tools/batbit_refunds.py", line 221, in do_newest_refunds
    pay_outs = payout_refunds(paid_out_ledger, minters_to_amount, key=key, is_test=is_test)
  File "/mnt/c/Users/beebl/PycharmProjects/teos-project-tools/batbit_refunds.py", line 179, in payout_refunds
    commit_refunds(refunds, key=key, is_test=is_test, max=500)
  File "/mnt/c/Users/beebl/PycharmProjects/teos-project-tools/batbit_refunds.py", line 151, in commit_refunds
    total_tez, base_tez, fee_tez, gas_tez = tz.transfer_batch(to_send=batch_list, is_test=is_test)
  File "/mnt/c/Users/beebl/PycharmProjects/teos-project-tools/util/transfer.py", line 37, in transfer_batch
    total_fee_tez, max_burn_tez = self._send_batch(operations)
  File "/mnt/c/Users/beebl/PycharmProjects/teos-project-tools/util/transfer.py", line 49, in _send_batch
    raise ex from None
  File "/mnt/c/Users/beebl/PycharmProjects/teos-project-tools/util/transfer.py", line 45, in _send_batch
    log.debug(pp.pformat(op.send(min_confirmations=1, ttl=60)))
  File "/home/moch/.pyenv/versions/3.8.13/envs/taco-tezos-project-tools/lib/python3.8/site-packages/pytezos/operation/group.py", line 339, in send
    res = opg.inject(min_confirmations=min_confirmations, num_blocks_wait=ttl)
  File "/home/moch/.pyenv/versions/3.8.13/envs/taco-tezos-project-tools/lib/python3.8/site-packages/pytezos/operation/group.py", line 404, in inject
    operations = self.shell.wait_operations(
  File "/home/moch/.pyenv/versions/3.8.13/envs/taco-tezos-project-tools/lib/python3.8/site-packages/pytezos/rpc/shell.py", line 188, in wait_operations
    raise StopIteration('Only %d of %d operations were included, stopping', len(operations), len(opg_hashes))
StopIteration: ('Only %d of %d operations were included, stopping', 0, 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/beebl/PycharmProjects/teos-project-tools/batbit_refunds.py", line 245, in <module>
    loop.run_until_complete(main())
  File "/home/moch/.pyenv/versions/3.8.13/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/mnt/c/Users/beebl/PycharmProjects/teos-project-tools/batbit_refunds.py", line 233, in main
    await do_newest_refunds(first_time=True, key="bbit", is_test=False)
RuntimeError: coroutine raised StopIteration
```

### PR DESCRIPTION
**Pull request by m-kus**
Resolves #297 

Based on
```
2022-04-26 01:58:16.147Z INFO shell Found new block BMMcivYhsijhCNq7PqqTVKyFAKWgCgow1WBF8K2NbUs8Xxv35aC (0 sec delay)
2022-04-26 01:58:17.102Z INFO shell Operation oopwxbhhcCfCm27Gg5aJ16jCG93f9BYLY71untJoEbktZQ55MpA is still in mempool
2022-04-26 01:58:17.622Z INFO shell Sleep 28 seconds until block BMMcivYhsijhCNq7PqqTVKyFAKWgCgow1WBF8K2NbUs8Xxv35aC is superseded
```

and given that operation was included in that block https://tzkt.io/oopwxbhhcCfCm27Gg5aJ16jCG93f9BYLY71untJoEbktZQ55MpA I think this is the case.

### CODE REVIEW

**Comment by steampoweredtaco** [comment]
FYI. I tried out this change with a ttl=60 for a batch operation of 41 simple xtz transations but the TTL of 60 timed out. The time out from start of simulation to failure was 10 minutes so that should of been only about 20 blocks right?  It seems unrealistic that it should take that long to simulate though, but either way the ttl didn't seem to be honored.  I'm not sure if the issue would be related to this change, but I thought I'd give ya a heads up before the PR is completed.

The line before the WARNING log line is timestamped for right before the send call and the WARNING line timestamp is the time the branched block, too old error occurs.

**Comment by m-kus** [comment]
Thanks for the heads up! Yeah, I think it's not directly related, but I'll try to fix it in this PR. Do I understand correctly that you have tried to send a batch and it was actually included in chain, but pytezos didn't detect that?

**Comment by steampoweredtaco** [comment]
> Thanks for the heads up! Yeah, I think it's not directly related, but I'll try to fix it in this PR. Do I understand correctly that you have tried to send a batch and it was actually included in chain, but pytezos didn't detect that?

For the **original** issue this PR is attached to that is correct, the batch operation made it on chain but was never confirmed by pytezos.

When I tried to use this change it never made it on-chain because of the TTL expiring even set to 60 with a batch operation of 41 xtz transfers, no contract calls. I think the TTL expired during the simulation.

**Comment by steampoweredtaco** [comment]
> @steampoweredtaco I have additionally made some optimizations that should decrease the building time of a batch. Separately, there can be an early return from the confirmation loop due to reorgs, but I will address that issue in another PR.

**Comment by steampoweredtaco** [comment]
> @steampoweredtaco I have additionally made some optimizations that should decrease the building time of a batch. Separately, there can be an early return from the confirmation loop due to reorgs, but I will address that issue in another PR.

Could you clarify for me what I should do if I get a reorg error before it is addressed? Does this mean the operation won't be submitted or that I need to retry confirming? If I want to retry confirming the operation because it still can pass, is the new hash on the error sufficient? How would I use it to reattempt the confirmation manually?

**Pull request merged**
